[package]
name = "rust-getting-started"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[lib]
name = "activity"
path = "src/activity_lib.rs" 

[dependencies]
chrono = "0.4" 
